version: '3.9'

services:
  #database:

  bot:
    container_name: inf_discord_bot
    build:
      context: ./bot
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 2
    restart: always

